"""created users

Revision ID: 1d12e4f7cb60
Revises: 
Create Date: 2026-03-20 12:33:00.946826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d12e4f7cb60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_id'), 'laboratories', ['id'], unique=False)
    op.create_table('researchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_researchers_id'), 'researchers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_researchers_id'), table_name='researchers')
    op.drop_table('researchers')
    op.drop_index(op.f('ix_laboratories_id'), table_name='laboratories')
    op.drop_table('laboratories')
    # ### end Alembic commands ###
